### PR TITLE
Add support for a=simulcast

### PR DESCRIPTION
**Pull request by ibc**
https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast

This PR completes the pending stuff in `simulcast.sdp` so coverage test works.

### CODE REVIEW

**Comment by ibc** [comment]
@clux I've a problem here. It happens that, in this PR, I've implemented the latest version of the simulcast draft ([version 7](https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast-07)), which looks as follows:

```
a=simulcast: send rid=1;2
```

Unfortunately, Firefox (stable and Nightly) implement an older [version 03](https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast-03) of the draft, which looks as follows:

```
a=simulcast: send 1:3
```

This is because, starting from version 04, the draft mandates usage of RID so there is no sense for the previous `rid=` field).

Is it ok for you if I extend the `simulcast` grammar so it admits both the old and the new BNF grammars and adds a `version` numeric field in the `names` array of the grammar (to write it different depending the version)?

**Comment by clux** [comment]
Hey there, this looks good.

> Is it ok for you if I extend the simulcast grammar so it admits both the old and the new BNF grammars and adds a version numeric field in the names array of the grammar (to write it different depending the version)?

This is fine with me if you can actually do that in a way that's functional and not enormous (having one large regex and one large parsing function is not great). Normally I'd do multiple formats by having multiple objects in the grammar that parses the same line. Then the first one that matches the regex takes precedence, but that does mean they can appear in different objects on the parsed area. Also, I'm not sure you can make the two regexes be mutually exclusive with this approach, you'd have to see I guess. If they're not, you run the risk of matching the old format in the new regex or vice versa.

**Comment by ibc** [comment]
> Normally I'd do multiple formats by having multiple objects in the grammar that parses the same line. Then the first one that matches the regex takes precedence, but that does mean the match can appear in different objects on the parsed result.

That should work for me. Let me check. Thanks!.

**Comment by ibc** [comment]
BTW I need to fix some stuff in both `imageattr` and `simulcast`. The current syntax assumes `send` before `recv` while it's valid to set `recv` before `send` (in fact, in simulcast is mandated for SDP answers).

**Comment by ibc** [comment]
Everything done in e76d47a82a595a1125094c96e4a581fcbe8f769b

**Comment by clux** [comment]
Yeah, this is great. Thanks a lot. Easy to remove support for the older spec at this point now that it is separated out like this.

Want me to release a minor with all the new grammar extensions you've added support for?

**Comment by ibc** [comment]
> Want me to release a minor with all the new grammar extensions you've added support for?

Yes please :)

**Comment by clux** [comment]
2.2.0 released with the last 3 prs. Thanks again for all of these :)

**Comment by ibc** [comment]
Thanks to you for all the help :)

**Pull request merged**
