### PR TITLE
Improves grammar rules and writer safety.

### PR DESCRIPTION
**Pull request by gpolitis**

### CODE REVIEW

**Comment by gpolitis** [comment]
Hi, could you please consider merging these changes? Alternatively, how about exposing the grammar so that depending modules can modify it? Thanks

**Comment by clux** [comment]
Hi, thanks for this. Yeah, the safety seems like a reasonable idea, I'll probably merge this later today or tomorrow then change those lines to `if (mLine[obj.name] != null)` to cover both undefined and null.

That said, `delete mLine[name]` will properly unset the object key if you were battling with the writer.

**Comment by gpolitis** [comment]
Awesome, thanks!

**Comment by clux** [comment]
Landed in sdp-transform@1.2.0

**Comment by gpolitis** [comment]
Actually, I think we need both the null check and the typeof check. Doesn't `mLine[obj.name] != null` throw a `ReferenceError` when mLine[obj.name] is not defined/never declared?

**Comment by clux** [comment]
Hm, not really. 

```js
var mLine = {};
var obj = {};
mLine[obj.name]; // undefined (despite key being undefined)
mLine[obj.name] != null; // false
```

That said, I am currently doing a rather pointless `n in o` check before excluding values manually set to null or undefined: https://github.com/clux/sdp-transform/commit/5b9c7b2867410a56d7f881352c1bcdebfac153d9. I should probably remove that.

**Pull request merged**
