### PR TITLE
Expose grammar object for customisation

### PR DESCRIPTION
**Pull request by reznikov**
Hey!
This PR allows to mutate the grammar before parsing. This is useful when dealing with custom sdp attributes.

### CODE REVIEW

**Comment by reznikov** [comment]
hey @clux,
would it be possible for you to review this PR, please?

**Review by clux — APPROVED** [review]
Thanks for this! Sorry missed it earlier. Elegant way of doing this imo.

**Comment by clux** [comment]
it's in 2.15.0 now 😄

**Comment by reznikov** [comment]
> it's in 2.15.0 now 😄

thanks! 🥳

**Pull request merged**
