### PR TITLE
Adds support for the ssrc-group media-level attribute.

### PR DESCRIPTION
**Pull request by gpolitis**

### CODE REVIEW

**Comment by clux** [comment]
Sensible. Thank you. Will merge later.

That said, feel free to add some tests for these things to ensure they keep working. Coveralls apparently does not see that this actually should decrease coverage, but the grammar abstraction object hides it (#27).

**Comment by clux** [comment]
Published in 1.2.1.
Btw @gpolitis, do you have an SDP containing these new attributes you added support for? I would really appreciate if you could commit just the raw sdps to the test directory :)

**Comment by gpolitis** [comment]
Awesome, thanks! I'm pasting an offer from the JSEP draft that includes both the `a=msid` and `a=ssrc-group` attributes. I'd be glad to add the test cases myself if you could buy me some more time.

```
v=0
o=- 4962303333179871722 1 IN IP4 0.0.0.0
s=-
t=0 0
a=msid-semantic:WMS
a=group:BUNDLE a1 v1
m=audio 56500 UDP/TLS/RTP/SAVPF 96 0 8 97 98
c=IN IP4 192.0.2.1
a=mid:a1
a=rtcp:56501 IN IP4 192.0.2.1
a=msid:47017fee-b6c1-4162-929c-a25110252400 f83006c5-a0ff-4e0a-9ed9-d3e6747be7d9
a=sendrecv
a=rtpmap:96 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:97 telephone-event/8000
a=rtpmap:98 telephone-event/48000
a=maxptime:120
a=ice-ufrag:ETEn1v9DoTMB9J4r
a=ice-pwd:OtSK0WpNtpUjkY4+86js7ZQl
a=ice-options:trickle
a=fingerprint:sha-256 19:E2:1C:3B:4B:9F:81:E6:B8:5C:F4:A5:A8:D8:73:04:BB:05:2F:70:9F:04:A9:0E:05:E9:26:33:E8:70:88:A2
a=setup:actpass
a=rtcp-mux
a=rtcp-rsize
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 urn:ietf:params:rtp-hdrext:sdes:mid
a=ssrc:1732846380 cname:EocUG1f0fcg/yvY7
a=candidate:3348148302 1 udp 2113937151 192.0.2.1 56500 typ host
a=candidate:3348148302 2 udp 2113937151 192.0.2.1 56501 typ host
a=end-of-candidates
m=video 56502 UDP/TLS/RTP/SAVPF 100 101
c=IN IP4 192.0.2.1
a=rtcp:56503 IN IP4 192.0.2.1
a=mid:v1
a=msid:61317484-2ed4-49d7-9eb7-1414322a7aae f30bdb4a-5db8-49b5-bcdc-e0c9a23172e0
a=sendrecv
a=rtpmap:100 VP8/90000
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=ice-ufrag:BGKkWnG5GmiUpdIV
a=ice-pwd:mqyWsAjvtKwTGnvhPztQ9mIf
a=ice-options:trickle
a=fingerprint:sha-256 19:E2:1C:3B:4B:9F:81:E6:B8:5C:F4:A5:A8:D8:73:04:BB:05:2F:70:9F:04:A9:0E:05:E9:26:33:E8:70:88:A2
a=setup:actpass
a=rtcp-mux
a=rtcp-rsize
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=ssrc:1366781083 cname:EocUG1f0fcg/yvY7
a=ssrc:1366781084 cname:EocUG1f0fcg/yvY7
a=ssrc-group:FID 1366781083 1366781084
a=candidate:3348148302 1 udp 2113937151 192.0.2.1 56502 typ host
a=candidate:3348148302 2 udp 2113937151 192.0.2.1 56503 typ host
a=end-of-candidates
```

**Comment by clux** [comment]
Appreciate it - and don't worry, these small PRs are good commute passtime :]

Added some simple test cases for them, and found that we didn't handle the `a=end-of-candidates` very nicely - it would likely be reordered  since it wasn't in the grammar. So that should be in 1.3.0 soon.

**Comment by gpolitis** [comment]
splendid!

**Pull request merged**
